### ISSUE TITLE
Xiaomi Double Wireless Wall Switch config

### ISSUE THREAD

**Issue by sjors98** [arachnetech/homebridge-mqttthing#209]
Hi! I'm having trouble configuring the Double Wall Switch from Xiaomi
I've made one button work, but I would like to have all buttons in one statelessprogrammableswitch

This works for one switch:
```json
{
    "accessory": "mqttthing",
    "type": "statelessProgrammableSwitch",
    "name": "Only Right Switch",
    "topics": {
        "getSwitch": {
            "topic": "zigbee2mqtt/0x00158d0004285a24",
            "apply": "switch(JSON.parse(message).click) { case 'right': return 1; break; case 'right_double': return 2; break; case 'right_long': return 'L'; break;}"
        }
    }
}
```

So I've went on to implement it for all switches but when I try this it does't recognize a button click
```json
{
    "accessory": "mqttthing",
    "type": "statelessProgrammableSwitch",
    "name": "All Switches",
    "topics": {
        "getSwitch": [
            "zigbee2mqtt/0x00158d0004285a24",
            "zigbee2mqtt/0x00158d0004285a24",
            "zigbee2mqtt/0x00158d0004285a24"
        ]
    },
    "switchValues": [
        "switch(JSON.parse(message).click) { case 'left': return 1; break; case 'left_double': return 2; break; case 'left_long': return 'L'; break;}",
        "switch(JSON.parse(message).click) { case 'right': return 1; break; case 'right_double': return 2; break; case 'right_long': return 'L'; break;}",
        "switch(JSON.parse(message).click) { case 'both': return 1; break; case 'both_double': return 2; break; case 'both_long': return 'L'; break;}"
    ]
}
```
Anyone that has already done this and can help me out with fixing this? :)

**Comment by nitej** [comment]
@sjors98, you want to format the “getSwitch” array as an array of “getSwitch” objects that are formatted like your single button example if you need to apply JavaScript to the message. Try this

```json
{
    "accessory": "mqttthing",
    "type": "statelessProgrammableSwitch",
    "name": "All Switches",
    "topics": {
        "getSwitch": [
            {
            "topic": "zigbee2mqtt/0x00158d0004285a24",
            "apply": "JSON.parse(message).click"
            },{
            "topic": "zigbee2mqtt/0x00158d0004285a24",
            "apply": "JSON.parse(message).click"
            },{
            "topic": "zigbee2mqtt/0x00158d0004285a24",
            "apply": "JSON.parse(message).click"
            }
         ]
      },
    "switchValues": [
        ["left”, “left_double”,”left_long"],
        ["right”,”right_double”,”right_long"],
        ["both”,”both_double”,”both_long"]
    ]
}
```

I also corrected the use of “switchValues” to simply your “apply” states

**Comment by sjors98** [comment]
It still doesn't work for me, not even the first (left button)
I did change the quotes so it's not that ;p

I'm wondering if https://github.com/arachnetech/homebridge-mqttthing/blob/master/index.js#L2309 Line 2309 is right? Shouldn't the 0 be i for the array? It loops through the first one (left) 3 times now right?

It's not the fix though because I did manage to change it locally and log the outcomes of the switchvalues. It does log the right and both now, but the button still doesn't work in homekit...

**Comment by sjors98** [comment]
Oh I think I forgot to return the JSON.parse (literally copied yours and pasted it)
Will try this piece of code tonight!

```json
{
    "accessory": "mqttthing",
    "type": "statelessProgrammableSwitch",
    "name": "Aqara Double Wall Switch",
    "topics": {
        "getSwitch": [
            {
            "topic": "zigbee2mqtt/0x00158d0004285a24",
            "apply": "return JSON.parse(message).click"
            },{
            "topic": "zigbee2mqtt/0x00158d0004285a24",
            "apply": "return JSON.parse(message).click"
            },{
            "topic": "zigbee2mqtt/0x00158d0004285a24",
            "apply": "return JSON.parse(message).click"
            }
         ]
      },
    "switchValues": [
        ["left", "left_double","left_long"],
        ["right","right_double","right_long"],
        ["both","both_double","both_long"]
    ]
}
```

**Comment by nitej** [comment]
Yes, I forgot to add the returns to the apply properties for each topic.

As for the code, line 2309 is checking whether the “switchValues” variable contains an array of arrays (or at least the first item in the array is an array). Otherwise, it treats “switchValues” normally and will apply those strings to all buttons in the device. By passing in an array of arrays, it lets you specify a set strings for each button in the device. Hope that makes more sense.

**Comment by sjors98** [comment]
This worked for me! Thank you so much! :)

**Comment by Rjayone** [comment]
There is the config for left-button switch:
`
            "type": "switch",
            "name": "Aqara Switch",
            "accessory": "mqttthing",
            "logMqtt": true,
            "topics": {
                "getOn": {
                    "topic": "zigbee2mqtt/**0x0**",
                    "apply": "return JSON.parse(message).state_left === 'ON' ? true : false;"
                },
                "setOn": {
                    "topic": "zigbee2mqtt/**0x0**/left/set",
                    "apply": "return JSON.stringify({state_left: (message ? \"ON\" : \"OFF\")});"
                }
            }
`
