### ISSUE TITLE
Upgrade to version 1.1.12 broke homebridge

### ISSUE THREAD

**Issue by m-rossi** [arachnetech/homebridge-mqttthing#261]
I recently upgraded to version to 1.1.12 from version 1.1.1 and it broke my system. Broke in this case means homebridge on my Raspberry Pi 3 runs fine, the log does not show any error. However in the Home.app the devices of homebridge are not responding. A downgrade of homebridge-mqttthing does not help.
If I remove the config homebridge is running fine again.

Please see the part of my configuration:
```json
{
    "accessory": "mqttthing",
    "type": "humiditySensor",
    "name": "Luftfeuchtigkeitssensor",
    "topics": {
        "getCurrentRelativeHumidity": {
            "topic": "zigbee2mqtt/aqara_sensor",
            "apply": "return parseFloat(JSON.parse(message).humidity);"
        },
        "getStatusLowBattery": {
            "topic": "zigbee2mqtt/aqara_sensor",
            "apply": "if (JSON.parse(message).battery < 20) return 1; else return 0;"
        }
    },
    "history": true
}, {
    "accessory": "mqttthing",
    "type": "temperatureSensor",
    "name": "Temperatursensor",
    "topics": {
        "getCurrentTemperature": {
            "topic": "zigbee2mqtt/aqara_sensor",
            "apply": "return parseFloat(JSON.parse(message).temperature);"
        },
        "getStatusLowBattery": {
            "topic": "zigbee2mqtt/aqara_sensor",
            "apply": "if (JSON.parse(message).battery < 20) return 1; else return 0;"
        }
    },
    "history": true
}, {
    "accessory": "mqttthing",
    "type": "airPressureSensor",
    "name": "Luftdrucksensor",
    "topics": {
        "getAirPressure": {
            "topic": "zigbee2mqtt/aqara_sensor",
            "apply": "return parseInt(JSON.parse(message).pressure);"
        },
        "getStatusLowBattery": {
            "topic": "zigbee2mqtt/aqara_sensor",
            "apply": "if (JSON.parse(message).battery < 20) return 1; else return 0;"
        }
    },
    "history": true
}
```

Can you find a configuration issue or provide another type of hint?

**Comment by m-rossi** [comment]
May https://github.com/arachnetech/homebridge-mqttthing/issues/253 is related?

**Comment by arachnetech** [comment]
You might need to restart your iOS device(s). Sometimes they just seem to get confused with Homebridge - it happened to me this morning.

**Comment by m-rossi** [comment]
I can confirm that can help sometimes. However, in this case it did not help.

**Comment by matbor** [comment]
I upgraded from Version 1.1.7 to 1.1.12 and all devices are showing up as ‘no response’ now, have been using the plugin for a long time without issue. Have tired rolling back to =1.1.7 but same error, very strange. Rebooting doesn’t help

**Comment by matbor** [comment]
Fixed mine, removed all references of,

 ` "history": true`

And it is working again.

**Comment by quiet2** [comment]
upgrade node to version 14 and more
this solved my problem:
`ERROR LOADING PLUGIN homebridge-mqttthing:
homebridge[32551]: [10/05/2020, 16:10:59] Error: Package exports for '/usr/lib/node_modules/homebridge-mqttthing/node_modules/uuid' do not define a '.' subpath
homebridge[32551]:     at resolveExports (internal/modules/cjs/loader.js:419:17)
homebridge[32551]:     at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
homebridge[32551]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
homebridge[32551]:     at Function.Module._load (internal/modules/cjs/loader.js:693:27)
homebridge[32551]:     at Module.require (internal/modules/cjs/loader.js:864:19)
homebridge[32551]:     at require (internal/modules/cjs/helpers.js:74:18)
homebridge[32551]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-mqttthing/node_modules/googleapis-common/build/src/apirequest.js:19:14)
homebridge[32551]:     at Module._compile (internal/modules/cjs/loader.js:971:30)
homebridge[32551]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
homebridge[32551]:     at Module.load (internal/modules/cjs/loader.js:822:32)

`

**Comment by m-rossi** [comment]
> Fixed mine by deleting all references of,
> 
> ` "history": true`
> 
> And it is working again. Also managed to upgrade again and working.
> 
> @m-rossi see if that works on yours.

@matbor Tried it, sadly it did not fix my issue. Thanks, anyway!

> upgrade nodejs to version 14 and more
> this solved my problem:
> `ERROR LOADING PLUGIN homebridge-mqttthing:
> homebridge[32551]: [10/05/2020, 16:10:59] Error: Package exports for '/usr/lib/node_modules/homebridge-mqttthing/node_modules/uuid' do not define a '.' subpath
> homebridge[32551]: at resolveExports (internal/modules/cjs/loader.js:419:17)
> homebridge[32551]: at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
> homebridge[32551]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
> homebridge[32551]: at Function.Module._load (internal/modules/cjs/loader.js:693:27)
> homebridge[32551]: at Module.require (internal/modules/cjs/loader.js:864:19)
> homebridge[32551]: at require (internal/modules/cjs/helpers.js:74:18)
> homebridge[32551]: at Object. (/usr/lib/node_modules/homebridge-mqttthing/node_modules/googleapis-common/build/src/apirequest.js:19:14)
> homebridge[32551]: at Module._compile (internal/modules/cjs/loader.js:971:30)
> homebridge[32551]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
> homebridge[32551]: at Module.load (internal/modules/cjs/loader.js:822:32)
> 
> `

@quiet2 As I said, the logfile is not showing any error, just this:

```
[5/11/2020, 10:05:39] Loaded plugin: homebridge-mqttthing
[5/11/2020, 10:05:39] Registering accessory 'homebridge-mqttthing.mqttthing'
[5/11/2020, 10:05:39] ---
...
[5/11/2020, 10:05:42] [Luftfeuchtigkeitssensor] Initializing mqttthing accessory...
[5/11/2020, 10:05:42] [Temperatursensor] Initializing mqttthing accessory...
[5/11/2020, 10:05:42] [Luftdrucksensor] Initializing mqttthing accessory...
```

@arachnetech Is there a way to provide more information for you? I think I tried the `-D` flag for homebridge, however it did not show any additional information in my case for `homebridge-mqttthing` if I remember correctly.

**Comment by arachnetech** [comment]
I think we're discussing multiple issues here.

`homebridge[32551]: [10/05/2020, 16:10:59] Error: Package exports for '/usr/lib/node_modules/homebridge-mqttthing/node_modules/uuid' do not define a '.' subpath` should be fixed by upgrading to a sufficiently new Node.js for recent Homebridge releases as I believe @quiet2 has confirmed.

#253 shouldn't be relevant as I've fixed it (I believe).

I believe @m-rossi 's original issue is the same as #262, which remains a mystery. Recent version of Homebridge sometimes seem to get upset by the references to Eve-specific attributes that are used for recording history as @matbor suggested.

I've experienced (on several occasions) situations where Homebridge and Homekit suddenly refuse to talk to each other for no apparent reason. I suspect this has nothing to do with MQTT-Thing. I've always fixed it by deleting my 'home' and homebridge cache/persist, changing my pin and uuid and repairing - but this is far more acceptable in a test configuration (where it usually happens for me) than in a _real_ home which is likely to have scenes and automations.

I did see a reference to the underlying HAPTypes library changing from JavaScript to TypeScript. I don't know whether this could make it less accepting of custom types (like the Eve types used for history).

I think you'll need the help of the Homebridge developers to diagnose this further.

**Comment by m-rossi** [comment]
> I believe @m-rossi 's original issue is the same as #262, which remains a mystery. Recent version of Homebridge sometimes seem to get upset by the references to Eve-specific attributes that are used for recording history as @matbor suggested.
> 
> I've experienced (on several occasions) situations where Homebridge and Homekit suddenly refuse to talk to each other for no apparent reason. I suspect this has nothing to do with MQTT-Thing. I've always fixed it by deleting my 'home' and homebridge cache/persist, changing my pin and uuid and repairing - but this is far more acceptable in a test configuration (where it usually happens for me) than in a _real_ home which is likely to have scenes and automations.

Thanks for linking to that issue. Seems that specific characteristics of a device may cause the issue. Maybe I am able to replicate that to my devices.

Before resetting my whole homebridge I want to try some more stuff.

> I did see a reference to the underlying HAPTypes library changing from JavaScript to TypeScript. I don't know whether this could make it less accepting of custom types (like the Eve types used for history).

I think that change happened quite recently with homebridge version 1.0 and the according hap-nodejs version, am I right? I was in the progress of carefully upgrading each plugin and later homebridge. However I was stopped by this issue here.

I just realized I have not posted the versions of the plugins and node
```
npm list -g --depth=1
/usr/lib
├─┬ homebridge@0.4.53
│ ├── chalk@1.1.3
│ ├── commander@2.8.1
│ ├── hap-nodejs@0.4.51
│ ├── node-persist@0.0.8
│ ├── qrcode-terminal@0.11.0
│ └── semver@5.0.3
...
homebridge-mqttthing@1.1.13
│ ├── fakegato-history@0.5.6
│ ├── homebridge-lib@4.7.0
│ └── mqtt@2.18.8
```
```
node --version
v12.16.3
```

**Comment by EjvindHald** [comment]
I am using newest version of Homebridge and newest mqtt-thing plugin with several topics with Eve history set to true. Everything is working fine with no issues.

**Comment by m-rossi** [comment]
A small update: I tried to play around with different apply-functions and removed and re-added the accessories with different names and so on.

I found out: The problem with not responding is the part with `airPressureSensor`:

```json
{
    "accessory": "mqttthing",
    "type": "airPressureSensor",
    "name": "Luftdrucksensor",
    "topics": {
        "getAirPressure": {
            "topic": "zigbee2mqtt/aqara_sensor",
            "apply": "return parseInt(JSON.parse(message).pressure);"
        },
        "getStatusLowBattery": {
            "topic": "zigbee2mqtt/aqara_sensor",
            "apply": "if (JSON.parse(message).battery < 20) return 1; else return 0;"
        }
    },
    "history": true
}
```

If I remove that part of the configuration. Homebridge is responding again. However it is somehow unreliable with updating the values of the two other sensors. Currently I can only get the initial values.

**Comment by EjvindHald** [comment]
I do not have airPressureSensor, so I could not test that type back then. But the work done with upgrade of Homebridge to new HAP version is really valued and needed.

**Comment by m-rossi** [comment]
I had some spare time today and upgraded my homebridge instance to `1.1.0` and later re-added the `airPressureSensor` and it worked! I have no clue why, but it worked.
