### ISSUE TITLE
Question about this plugin.

### ISSUE THREAD

**Issue by rikray02** [arachnetech/homebridge-mqttthing#412]
Hello,

I Received this error (warning) message since i have updated Homebridge to 1.3.0. So, the plugin homebridge-mqtt-power-consumption-log-tasmota is very old and i believe that is not supported.  I would to know if mqttthing plugin can support writing a consumption to a log file.

Thanks for your reply.  

[2/21/2021, 11:02:12 AM] [homebridge-mqtt-power-consumption-log-tasmota] This plugin generated a warning from the characteristic 'Status Active': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.

Information Système
Fuseau Horaire GMT-0500
OS macOS
Hostname Mac-mini-de-Richard.local
IPv4 (en0) 10.0.1.15
IPv6 (en0) fe80::1404:1660:252c:80bf
Version de Node.js v15.5.0
Version de Npm v7.3.0
Répertoire de stockage /Users/richardraymond/.homebridge
Répertoire de la Config /Users/richardraymond/.homebridge/config.json
Executer comme Service Yes

**Comment by Shaky50** [comment]
Au cas où:
In case you haven’t heard anything about this issue, please look at post “Warnings after homebridge 1.3.1 upgrade #414”.
It is the same problem and it’s being looked at by the owner/creator of the plug (very efficient and professional people it seems).

to avoid seeing all the messages and in case it indeed could affect HomeKit as warned, I simply rolled back HB o my previous version (1.1.7).

Cheers, Henri

**Comment by arachnetech** [comment]
There's a beta version which should fix the warnings, but I haven't had a chance to test it fully. It is **1.1.26-beta.0** if you get a chance to try it.

**Comment by rikray02** [comment]
Hello,
Thanks for the fix and your support. Unfortunately for me it didn't change anything, the warning message is still present. I greatly appreciate your help.
Richard

**Comment by arachnetech** [comment]
Did you definitely test with the beta version? You would need to have installed it manually - the latest general release is unchanged?

**Comment by rikray02** [comment]
Oh, I'm hot sure. See picture below.
But basically my problem comes from another pluggin, the homebridge-mqtt-power-consumption-log-tasmota. I wanted to know if the pluggin  homebridge-mqttthing can log power consumption to files like the homebridge-mqtt-power-consumption-log-tasmota pluggin does? I apologize for the confusion.

![image](https://user-images.githubusercontent.com/42678689/110207734-809b9f80-7e53-11eb-9c04-3c9f961ad868.png)

**Comment by arachnetech** [comment]
Version 1.1.28 should be better.
